//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ApartmentsEntities : DbContext
    {
        public ApartmentsEntities()
            : base("name=ApartmentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApartmentDetail> ApartmentDetails { get; set; }
        public virtual DbSet<CityMaster> CityMasters { get; set; }
    
        public virtual ObjectResult<getApartmentDetails_Result> getApartmentDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getApartmentDetails_Result>("getApartmentDetails");
        }
    }
}
